version: '3'
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: hosasbets_db
    ports:
        - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=HosasBets123456!
      - MSSQL_PID=Developer
  hosasbets.matches:
    container_name: hosasbets.matches
    build: ./src/HosasBets.Matches
    ports:
      - 5502:5502
  hosasbets.users:
    container_name: hosasbets.users
    build: ./src/HosasBets.Users
    ports:
      - 5501:5501
  hosasbets.bets:
    container_name: hosasbets.bets
    build: ./src/HosasBets.Bets
    ports:
      - 5503:5503
  hosasbets.odds:
    container_name: hosasbets.odds
    build: ./src/HosasBets.Odds
    ports:
      - 5504:5504